config.load_autoconfig(False)
config.set('colors.webpage.darkmode.enabled', True)
config.bind("<Ctrl-n>", "completion-item-focus --history next", mode="command")
config.bind("<Ctrl-p>", "completion-item-focus --history prev", mode="command") 
config.set('statusbar.show', 'never')
config.set('tabs.show', 'never')
config.set('url.default_page', 'https://www.google.com')
config.set('url.searchengines', {'DEFAULT': 'https://www.google.com/search?q={}'})
config.set('url.start_pages', 'https://www.google.com')

