# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[directory]
truncate_to_repo = false

[git_branch]
format = ' [($symbol$branch(:$remote_branch))]($style)'
symbol = ' '
style = 'bold purple'

[cmd_duration]
format = ''

[git_status]
disabled = true
