# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = true

[directory]
truncate_to_repo = false

[git_branch]
format = '\([$symbol$branch]($style)\) '
symbol = ''
style = 'bold #c4a7e7'

[cmd_duration]
format = ''

[git_status]
disabled = true

format = """
$directory\
$vcsh\
$git_branch\
"""

[character]
disabled = true

