return {
	"rose-pine/neovim",
	name = "rose-pine",
	lazy = false,
	priority = 999,
	opts = {},
	config = function()
		local opts = {
			variant = "main",
			dark_variant = "main",
			dim_inactive_windows = false,
			disable_float_background = true,

			styles = {
				bold = true,
				italic = true,
				transparency = true,
			},

			groups = {
				background = "base",
				background_nc = "_experimental_nc",
				panel = "surface",
				panel_nc = "base",
				border = "highlight_med",
				comment = "muted",
				link = "iris",
				punctuation = "subtle",

				error = "love",
				hint = "iris",
				info = "#FFFFFF",
				warn = "#fc9403",

				headings = {
					h1 = "iris",
					h2 = "foam",
					h3 = "rose",
					h4 = "gold",
					h5 = "pine",
					h6 = "foam",
				},
			},
			highlight_groups = {
				CursorLine = { bg = "#26233a", fg = "none" },
				StatusLine = { fg = "love", bg = "love", blend = 0 },
				Search = { bg = "gold", inherit = false },
				PmenuSel = { bg = "none", fg = "iris" },
				GitSignsAdd = { fg = "#5beb82", bg = "none" },
				GitSignsChange = { fg = "rose", bg = "none" },
				GitSignsDelete = { fg = "love", bg = "none" },
				FloatBorder = { bg = "none", fg = "highlight_med" },
				LazyButton = { bg = "none", fg = "#e0def4" },
				LazyH1 = { bg = "none", fg = "#e0def4" },
				LazyButtonActive = { bg = "none", fg = "#e0def4" },
				LazySpecial = { bg = "none", fg = "#e0def4" },
				DiffAdd = { bg = "none", fg = "#5beb82", blend = 0, nocombine = true },
				DiffChange = { bg = "none", fg = "foam", blend = 0, nocombine = true },
				DiffDelete = { bg = "none", fg = "love", blend = 0, nocombine = true },
				DiffText = { bg = "none", fg = "white" },
				GitSignsDeletePreview = { bg = "NONE", fg = "love", blend = 0, nocombine = true },
				GitSignsAddPreview = { bg = "NONE", fg = "#5beb82", blend = 0, nocombine = true },
				GitSignsAddLn = { bg = "NONE", fg = "none", blend = 0, nocombine = true },
				NoiceCmdlinePopupBorderSearch = { bg = "none", fg = "highlight_med" },
				NoiceCmdlineIconSearch = { bg = "none", fg = "#e0def4" },
				NoiceCmdLinePopupTitle = { bg = "none", fg = "#908caa" },
				NoiceCursor = { fg = "text", bg = "highlight_high" },
				NoiceCmdlinePopupBorder = { bg = "none", fg = "highlight_med" },
				NotifyERRORBorder = { fg = "#eb6f92" },
				NotifyWARNBorder = { fg = "#f6c177" },
				NotifyINFOBorder = { fg = "#c4a7e7" },
				NotifyDEBUGBorder = { fg = "#eb6f92" },
				NotifyTRACEBorder = { fg = "#c4a7e7" },
				NotifyINFOTitle = { bg = "none", fg = "#c4a7e7" },
				NotifyINFOIcon = { bg = "none", fg = "#c4a7e7" },
				NotifyWARNTitle = { bg = "none", fg = "#f6c177" },
				NotifyWARNIcon = { bg = "none", fg = "#f6c177" },
				NotifyDEBUGTitle = { bg = "none", fg = "#eb6f92" },
				NotifyDEBUGIcon = { bg = "none", fg = "#eb6f92" },
				NotifyTRACETitle = { bg = "none", fg = "#c4a7e7" },
				NotifyTRACEIcon = { bg = "none", fg = "#c4a7e7" },
				NotifyERRORTitle = { bg = "none", fg = "#eb6f92" },
				NotifyERRORIcon = { bg = "none", fg = "#eb6f92" },
				NoiceVirtualText = { bg = "none", fg = "subtle" },
				NeogitDiffAddHighlight = { bg = "none", fg = "#5beb82" },
			},
		}
		require("rose-pine").setup(opts)
		vim.cmd("colorscheme rose-pine")
	end,
}
