format = """
$directory\
$git_branch\
$character\
"""

add_newline = false

[directory]
truncate_to_repo = false
read_only = ''
truncation_symbol = '…/'

[git_branch]
format = '[$symbol$branch]($style) '
symbol = ''
style = 'bold #c4a7e7'

[cmd_duration]
format = ''

[character]
success_symbol = '[❯](bold purple)'
error_symbol = '[❯](bold purple)'

[package]
disabled = true
